### ISSUE TITLE
Support for multiple classifications

### ISSUE THREAD

**Issue by cgendreau** [DINA-Web/taxonomy#2]
In the first document for the Taxonomy API and in some other documents (other Google Docs) related to taxonomy it seems that the taxonomy module **shall** support multiple classifications.

It would be very interesting and valuable to know what is the use case, in the context of collection management, that supports and explains this requirement.

I can see why this is valuable for taxonomic research but for collection management I have to admit that I struggle to find the problem it solves ( but I'm not a collection manager).

**Comment by kcranston** [comment]
In the AAFC environment, we will be managing multiple collections (plants, insects, fungi, etc) but want to be able to integrate data across the collections. Setting aside the research use cases, I expect that each collection will want control over the taxonomy related to their specimens. 

Will each collection have its own DINA instance? If so, then I also struggle to see the non-research use case for multiple collections. If we expect to have multiple collections in a single DINA instance, then I can see a potential need for multiple taxonomies. (Potential need, because we could have one single backbone taxonomy and allow each collection to manage the part of it relevant to their collection. This becomes complicated if there is taxonomic overlap between collections).

**Comment by mikkohei13** [comment]
Multiple classifications can be needed if the system is used by several collections handling same taxonomic group, but following different classifications (e.g. one using a static published list, another updating it regularly with latest changes). Research use case have been mentioned, but not thoroughly documented (as far as I remember).

However multiple classifications are not priority for NRM, there's no need to handle them for at least a year probably.

**Comment by kcranston** [comment]
Noting that AAFC does have a use case with overlapping taxonomies - we have two fungal collections (one with dried herbarium specimens, and one with live cultures).

**Comment by cgendreau** [comment]
I think the taxonomy module can be simplified by handling a single classification and it would still possible to manage multiple classification by having multiple instances.
But, it could be difficult to eventually merge them if they overlap (and they will) and it is also more difficult to query if you want to query all classifications (but it could be solved by a search module).

**Comment by kcranston** [comment]
I have some high-level questions about overall DINA structure and suspect that we might not have the same assumptions about this structure. I've created an issue in the doc repo to discuss: https://github.com/DINA-Web/documentation/issues/3

**Comment by gnewton** [comment]
We will not have multiple instances.

Going with an api that supports multiple taxonomies is better than bolting
it on later.
James agrees.
And a year out for Stockholm means it should be in the api now.
Glen

**Comment by kcranston** [comment]
Seems there is general agreement about needing to support multiple classifications within a single DINA instance (and consensus about the composition of a 'DINA instance' - see https://github.com/DINA-Web/documentation/issues/3).

I am closing this, and we can move on to designing a data model and API that supports multiple classifications (noting that there are still many decisions about _how_ we support them).
